name: Deploy Documents
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set-up Node
        uses: actions/setup-node@v3.2.0
        with:
          node-version: "20.x"
      - run: npm install
      - run: npm run doc
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: gh-pages
          build_dir: documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}